language: ruby
rvm:
  - 2.2.1
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - bundle exec rake test
  - bundle exec rspec
  - bundle exec rake cucumber
before_script:
  - psql -c 'create database beast_test' -U postgres
addons:
    code_climate:
        repo_token: 624173816fd8e77312a169ea5ee7d904ea844382b8182147def2eeac9f0160b1
